### ISSUE TITLE
can't load data

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [ErfanRht/MovieLab#10]
App can't load data. what do i do, try again?
I always get this message after starting the app
![photo1661017923](https://user-images.githubusercontent.com/61406324/185761903-ba384e06-4395-4de9-9635-c956216db147.jpeg)
,

**Comment by KiritoStorm** [comment]
I just installed the app and I always get that error on the loading screen.
Maybe that's a simular problem.

![Internet_not_working](https://user-images.githubusercontent.com/46503102/185769235-f994a9d4-b383-437b-88d6-480a48f4c064.jpg)

**Comment by jotbeh** [comment]
> I just installed the app and I always get that error on the loading screen. Maybe that's a simular problem.
> 
> ![Internet_not_working](https://user-images.githubusercontent.com/46503102/185769235-f994a9d4-b383-437b-88d6-480a48f4c064.jpg)

Same issue here! Hope it can be fixed, the screenshots look very promising.

**Comment by TeaqariaWTF** [comment]
![Screenshot_20220821-111211_MovieLab](https://user-images.githubusercontent.com/90970076/185782130-c9ac656a-ebaa-49fb-9695-cef711d8e875.png)

I'm getting the same error, I hope this problem is solved

**Comment by ErfanRht** [comment]
Oh sorry, I missed that.

Fixed in [2.0.4](https://github.com/ErfanRht/MovieLab/releases/tag/v2.0.4). Check it out!

**Comment by mondlicht-und-sterne** [comment]
> Oh sorry, I missed that.
> 
> Fixed in [2.0.4](https://github.com/ErfanRht/MovieLab/releases/tag/v2.0.4). Check it out!

Yeah i tested tje apk and it works now ;)

**Comment by Gottarocket** [comment]
Any seasons when opened shows unexpected error. Go to show like sandman click on season 1 click on episode

**Comment by ErfanRht** [comment]
> Any seasons when opened shows unexpected error. Go to show like sandman click on season 1 click on episode

Yes, it seems like we're having a problem there!

**Comment by ErfanRht** [comment]
It's been fixed in [2.0.6](https://github.com/ErfanRht/MovieLab/releases/tag/v2.0.6). Check it out!

**Comment by Lavin-tom** [comment]
No, problem is still there. but occur only when search some movies :( 
Also now history is showing only upto three movies.

**Comment by ErfanRht** [comment]
> No, problem is still there. but occur only when search some movies :( Also now history is showing only upto three movies.

I'm afraid I couldn't find the problem, can you send a screenshot of the problem?

**Comment by Lavin-tom** [comment]
![ezgif com-optimize](https://user-images.githubusercontent.com/53207510/188261317-aa8c6a70-d846-4ea8-812d-cee3d6cfd574.gif)

**Comment by ErfanRht** [comment]
Thanks for pointing that out @Lavin-tom .
I will fix it in the next update.

**Comment by Gottarocket** [comment]
Internet not connected issue. App jas internet no data turned off in settings. Wifi mobile network has same issue. Vpn without vpn . Different locations same issue. Force stop and opened still shows issue. Want to confirm here if its only me because there is no matrix channel or forum to ask this simple query.

**Comment by Gottarocket** [comment]
`errorText: _loadingStatus == RequestResult.FAILURE_SERVER_PROBLEM
              ? 'An unexpected error occurred while loading data.'
              : 'Your internet connection is not working.',`

Maybe its having some issue on server so its showing this issue instead of An unexpected error occurred while loading data

**Comment by rocket-pig** [comment]
I have same problem.

I see this in readme: "To run this app, you must get an IMDb api key and put it in lib\modules\api\api_keys.dart"

..maybe there needs to be a configuration page where user can enter API key?

**Comment by ErfanRht** [comment]
> I have same problem.
> I see this in readme: "To run this app, you must get an IMDb api key and put it in lib\modules\api\api_keys.dart"
> ..maybe there needs to be a configuration page where user can enter API key?

Thank you for mentioning that.
I updated the build documentation and made it clearer for now.
But your idea makes sense and can be added to the app in the near future.

**Comment by rocket-pig** [comment]
..does this mean that anyone downloading the precompiled app (from F‐Droid etc) will always have these connection problems, until they can enter their own API key?

**Comment by ErfanRht** [comment]
No, this has nothing to do with users, only developers who wants to clone and run/build the project on their own computer would need to use their own api key and users won't have this problem.

**Comment by Kreuger** [comment]
This error has come back again.
